"""Portraits for the study follow-up (2026-09-26): the four new items, the Tuning Fork and Item
Pouch Workshop cards, and the Holo shelf cards (kept in the "tools" sheet). Same 14x14 ASCII
format and palette letters as gen_cards.py (which merges these dicts). Original art, authored
as code.
"""

ITEMS = {
    # A raffle ticket with a big question mark: a 1 in 5 chance of a Joker.
    "lucky_draw": [
        "..............",
        "..............",
        ".PPPPPPPPPPPP.",
        ".PppppppppppR.",
        ".Pp...yYY..pR.",
        "..p..y..Yo.p..",
        ".Pp.....Yo.pR.",
        ".Pp....YYo.pR.",
        "..p...Yo...p..",
        ".Pp...YO...pR.",
        ".Pp........pR.",
        ".Pp...Yo...pR.",
        ".PRRRRRRRRRRR.",
        "..............",
    ],
    # A rubber stamp over a lilac question-mark imprint.
    "mystery_stamp": [
        ".....dEEd.....",
        ".....EeeE.....",
        ".....EeeE.....",
        "......Ee......",
        "......Ee......",
        "...dddddddd...",
        "..PPPPPPPPPP..",
        "..PppppppppR..",
        "..RRRRRRRRRR..",
        "..............",
        ".....vvvv.....",
        "........v.....",
        "......vv......",
        "......v.......",
    ],
    # A coin stamped "x2": double your Credits.
    "double_down": [
        "..............",
        "....kkkkkk....",
        "..kkyyyyyYkk..",
        ".kyyYYYYYYYok.",
        ".kyYYYYYkkYok.",
        "kyYkYkYYYYkOok",
        "kyYYkYYYYkYOok",
        "kyYkYkYYkYYOok",
        "kYYYYYYYkkkOok",
        ".kYYYYYYYYOOk.",
        ".kooYYYYYOOOk.",
        "..kkoooooOkk..",
        "....kkkkkk....",
        "..............",
    ],
    # A little ghost floating over a line of blocks: an extra line that is not there.
    "phantom_line": [
        "....hhhhhh....",
        "...hiiiiiih...",
        "..hiiiiiiiih..",
        "..hiwkiiwkih..",
        "..hiwkiiwkih..",
        "..hiiiiiiiih..",
        "..hiiiiiiiih..",
        "..hih.hh.hih..",
        "..............",
        "SSSSSSSSSSSSSS",
        "SsSsSsSsSsSsSb",
        "bbbbbbbbbbbbbb",
        "..............",
        "..............",
    ],
}

TOOLS = {
    # A steel tuning fork ringing: a Joker levels up.
    "tuning_fork": [
        "..x....x......",
        "..x....x......",
        "..xX...xX.....",
        "..xX...xX..s..",
        "..xX...xX.s.s.",
        "..xX...xX..s..",
        "..xXXXXxX.....",
        "...xxxxX......",
        ".....xX.......",
        ".....xX.......",
        ".....xX.......",
        "....zxXz......",
        "....zZZz......",
        "..............",
    ],
    # A pink pouch with a mint plus: one more item slot.
    "item_pouch": [
        ".....e..e.....",
        "......ee......",
        ".....EEEE.....",
        "....dEEEEd....",
        "...PPPPPPPP...",
        "..PpppppppPr..",
        ".PppppMMpppPr.",
        ".PppppMMpppPr.",
        ".PppMMMMMMpPr.",
        ".PppMMMMMMpPr.",
        ".PppppMMpppPr.",
        ".PppppMMpppPr.",
        "..PPPPPPPPPr..",
        "...rrrrrrrr...",
    ],
    # --- Holo shelf ---
    # A film strip whose frames are printed in negative.
    "negative_film": [
        "..............",
        "..............",
        "tttttttttttttt",
        "twtwtwtwtwtwtw",
        "tttttttttttttt",
        "tcccctttSSSStt",
        "tcttcttSwwSStt",
        "tcttcttSwwSStt",
        "tcccctttSSSStt",
        "tttttttttttttt",
        "twtwtwtwtwtwtw",
        "tttttttttttttt",
        "..............",
        "..............",
    ],
    # A red wax seal with a looping arrow: trigger again.
    "again_seal": [
        "....RRRRRR....",
        "..RRrrrrrrRR..",
        ".RrrPPPPPPrrR.",
        ".RrPPwwwwPPrR.",
        "RrPPwPPPPwPPrR",
        "RrPwPPPPPPwwwR",
        "RrPwPPPPPPPwPR",
        "RrPwPPPPPPPPrR",
        "RrPPwPPPPwPPrR",
        ".RrPPwwwwPPrR.",
        ".RrrPPPPPPrrR.",
        "..RRrrrrrrRR..",
        "...RR....RR...",
        "..RR......RR..",
    ],
    # A blueprint with a gold star in the corner: every family levels up.
    "master_schematic": [
        "..............",
        "bbbbbbbbbbbbb.",
        "bSSSSSSSSSSSb.",
        "bSwwwSSwSSSSb.",
        "bSwSwSSwSSSSb.",
        "bSwwwSSwwwwSb.",
        "bSSSSSSSSSwSb.",
        "bSwwwwwSSSwSb.",
        "bSSSSSSSSSSSb.",
        "bbbbbbbbbbYbb.",
        "..........YYY.",
        ".........YYyYY",
        "..........YYY.",
        "..........Y.Y.",
    ],
    # A golden tuning fork ringing: every scoring Joker levels up.
    "master_tuning": [
        "..y....y......",
        "..y....y...y..",
        "..yO...yO.y.y.",
        "..yO...yO..y..",
        "..yO...yO.....",
        "..yO...yO..w..",
        "..yOOOOyO.www.",
        "...yyyyO...w..",
        ".....yO.......",
        ".....yO.......",
        ".....yO.......",
        "....oyOo......",
        "....oOOo......",
        "..............",
    ],
    # A lilac crate with a star: a Legendary Joker.
    "legend_crate": [
        "..............",
        "..hhhhhhhhhh..",
        ".hiiiiiiiiiiH.",
        ".hHHHHHHHHHHH.",
        ".hiHHHiiHHHiH.",
        ".hiiHyYYyHiiH.",
        ".hiiiYwwYiiiH.",
        ".hiiHyYYyHiiH.",
        ".hiHHHiiHHHiH.",
        ".hHHHHHHHHHHH.",
        ".hiiiiiiiiiiH.",
        "..HHHHHHHHHH..",
        "..............",
        "..............",
    ],
    # A card and its see-through double: a Negative copy.
    "hologram": [
        "....QQQQQQQQ..",
        "....QqqqqqqQ..",
        "..cccccccqqQ..",
        "..cCCCCCcqqQ..",
        "..cCYYYCcqqQ..",
        "..cCYwYCcqqQ..",
        "..cCYYYCcqqQ..",
        "..cCCCCCcqqQ..",
        "..cCPPPCcqqQ..",
        "..cCCCCCcQQQ..",
        "..ccccccc.....",
        "..............",
        "..............",
        "..............",
    ],
}
