"""Portraits for the color and form Jokers (owner request, 2026-09-26): a common and a rare for
every block color and every piece form. Same 14x14 ASCII format and palette letters as
gen_cards.py (which merges this dict). Original art, authored as code.
"""

JOKERS = {
    # --- Color commons ---
    # A red rotating beacon throwing light.
    "red_alert": [
        "..p...p...p...",
        "...p..p..p....",
        "..............",
        ".....rrrr.....",
        "....rPPPPr....",
        "...rPwPPPPr...",
        "...rPwPPPPr...",
        "...rPPPPPPr...",
        "..rrrrrrrrrr..",
        "..XxxxxxxxxX..",
        "..XXXXXXXXXX..",
        "..............",
    ],
    # An orange slice.
    "citrus_twist": [
        "....NNNNNN....",
        "...NnnnnnnN...",
        "..NnwnnnnwnN..",
        ".NnnnwnnwnnnN.",
        ".NnnnnwwnnnnN.",
        ".NwwwwwwwwwwN.",
        ".NnnnnwwnnnnN.",
        ".NnnnwnnwnnnN.",
        "..NnwnnnnwnN..",
        "...NnnnnnnN...",
        "....NNNNNN....",
    ],
    # A lemon with its leaf.
    "lemon_drop": [
        ".......g......",
        "......gM......",
        ".....YYYYo....",
        "...yYYYYYYo...",
        "..yYwYYYYYYo..",
        ".yYwYYYYYYYYo.",
        ".yYYYYYYYYYYo.",
        ".YYYYYYYYYYYo.",
        "..YYYYYYYYYo..",
        "...oYYYYYoo...",
        ".....oooo.....",
    ],
    # A sprout in a clay pot.
    "green_thumb": [
        "......m.......",
        ".....mMm.m....",
        "....mMMgmMm...",
        "......g.mM....",
        "......g.......",
        "......g.......",
        "...EEEEEEEE...",
        "...eEEEEEEd...",
        "....eEEEEd....",
        "....eEEEEd....",
        ".....dddd.....",
    ],
    # A ripe plum.
    "plum_job": [
        "......G.......",
        ".....Gm.......",
        "....hhGhh.....",
        "...hiiihhH....",
        "..hiwiihhhH...",
        "..hiiihhhhH...",
        "..hhhhhhhhH...",
        "..hhhhhhhHH...",
        "...hhhhhHH....",
        "....HHHHH.....",
    ],
    # --- Color rares ---
    # A swollen red star and its little blue planet.
    "red_giant": [
        "....rrrrrr....",
        "...rPPPPPPr...",
        "..rPppPPPPPr..",
        ".rPpwpPPPPPPr.",
        ".rPppPPPPPPPr.",
        ".rPPPPPPPPPPr.",
        ".rPPPPPPPPPrr.",
        ".rPPPPPPPPPrr.",
        "..rPPPPPPPrr..",
        "...rrPPPrrr...",
        "....rrrrrr..s.",
        "............sS",
    ],
    # The sun sinking into the sea.
    "sunset_glow": [
        "..n...n...n...",
        "...n..n..n....",
        "..............",
        "....NNNNNN....",
        "...NnnnnnnN...",
        "..NnnyyynnnN..",
        "..NnnnnnnnnN..",
        "UUUUUUUUUUUUUU",
        "uLuLuLuLuLuLuL",
        "LuLuLuLuLuLuLu",
        "uuuuuuuuuuuuuu",
    ],
    # A blazing sun with flares.
    "solar_flare": [
        "......y.......",
        "..y...Y...y...",
        "...Y..Y..Y....",
        "....YYYYYo....",
        "..yYYyyyYYo...",
        "yYYYyyyyyYYYoo",
        "..YYyyyyyYYo..",
        "...YYyyyYYo...",
        "....oYYYoo....",
        "...o..Y..o....",
        "..o...o...o...",
        "......o.......",
    ],
    # A tall pine tree.
    "evergreen": [
        "......M.......",
        ".....MMg......",
        "....MmMMg.....",
        "...MMMMMMg....",
        ".....MMMg.....",
        "....MmMMMg....",
        "...MMMMMMMg...",
        "..MMMMMMMMMg..",
        "....MmMMMMg...",
        "..MMMMMMMMMMg.",
        ".MMMMMMMMMMMMg",
        "......dd......",
        "......dd......",
        "....DDDDDD....",
    ],
    # A whale's tail over deep water.
    "deep_blue": [
        ".bb........bb.",
        ".bSb......bSb.",
        "..bSb....bSb..",
        "...bSbbbbSb...",
        "....bSSSSb....",
        ".....bSSb.....",
        ".....bSSb.....",
        "......bb......",
        "ssSSssSSssSSss",
        "SSbbSSbbSSbbSS",
        "bbBBbbBBbbBBbb",
    ],
    # A gold crown on purple velvet.
    "royal_purple": [
        "..y....y....y.",
        ".yYy..yYy..yYy",
        "..Y....Y....Y.",
        "..YY..YYY..YY.",
        "..YhYYYhYYYhY.",
        "..YhhhhhhhhhY.",
        "..YhihhhhihhY.",
        "..YhhhhhhhhhY.",
        "..YYYYYYYYYYY.",
        "..ooooooooooo.",
    ],
    # --- Form commons ---
    # One block alone under the moon.
    "lone_wolf": [
        "..........yy..",
        ".........yYY..",
        ".........yY...",
        "..........yy..",
        "..............",
        "..............",
        "....SSSSSS....",
        "....SsssSb....",
        "....SsSSSb....",
        "....SsSSSb....",
        "....Sbbbbb....",
        "..............",
        "xxxxxxxxxxxxxx",
    ],
    # A golf ball on a T-shaped tee.
    "tee_time": [
        "....wwww......",
        "...wwcwww.....",
        "...wcwwcw.....",
        "...wwwwww.....",
        "....wwww......",
        "...EEEEEE.....",
        ".....eE.......",
        ".....eE.......",
        ".....eE.......",
        "......E.......",
        "..............",
        "MMMMMMMMMMMMMM",
    ],
    # A zigzag piece darting sideways.
    "zigzagger": [
        "..............",
        "....mmmmmmmm..",
        "....mMMMMMMg..",
        "....mMMMMMMg..",
        "mmmmmMMMgggg..",
        "mMMMMMMg..w.w.",
        "mMMMMMMg.w.w..",
        "gggggggg..w.w.",
    ],
    # A pink plus piece.
    "plus_side": [
        ".....PPPP.....",
        ".....PppP.....",
        ".....PppP.....",
        ".PPPPPppPPPPr.",
        ".PppppppppppR.",
        ".PppppppppppR.",
        ".rrrrPppPrrrR.",
        ".....PppP.....",
        ".....PppP.....",
        ".....rrrr.....",
    ],
    # --- Form rares ---
    # A single cut diamond.
    "solitaire": [
        "...ssssssss...",
        "..swwsSSsSSb..",
        ".swsSSsSSsSSb.",
        "bbbbbbbbbbbbbb",
        ".bSsSSsSSsSb..",
        "..bSsSSsSSb...",
        "...bSsSSsb....",
        "....bSSSb.....",
        ".....bSb......",
        "......b.......",
    ],
    # A heavy barbell.
    "barbell": [
        ".XX........XX.",
        "XxxX......XxxX",
        "XxxX......XxxX",
        "XxxXzzzzzzXxxX",
        "XxxXZZZZZZXxxX",
        "XxxX......XxxX",
        "XxxX......XxxX",
        ".XX........XX.",
    ],
    # A big L piece with room to spare.
    "elbow_room": [
        "...YYYY.......",
        "...YyyY.......",
        "...YyyY.......",
        "...YyyY.......",
        "...YyyY.......",
        "...YyyYYYYYY..",
        "...YyyyyyyyY..",
        "...YyyyyyyyY..",
        "...YYYYYYYYY..",
        "..............",
        "..w.......w...",
        ".www.....www..",
    ],
    # Four square blocks under a flag: the town hall.
    "town_square": [
        ".......P......",
        ".......PP.....",
        ".......PPP....",
        ".......x......",
        "..SSSSSSSSSS..",
        "..SssSbSssSb..",
        "..SsSSbSsSSb..",
        "..SbbbbSbbbb..",
        "..SSSSSSSSSS..",
        "..SssSbSssSb..",
        "..SsSSbSsSSb..",
        "..SbbbbSbbbb..",
    ],
    # A roaring green dinosaur.
    "t_rex": [
        "....gMMMMMMg..",
        "...gMMkMMMMMg.",
        "...MMMMMMMMMM.",
        "...MMMMMMMMMM.",
        "...MMMMwwwwww.",
        "...MMMM.......",
        "..MMMMMMMM....",
        ".MMMMMMM.MM...",
        "MMMMMMMM......",
        "MgMMMMMM......",
        "g..MMMMM......",
        "...MM..MM.....",
        "...gg..gg.....",
    ],
    # A zigzag bolt of lightning.
    "lightning_bolt": [
        ".......YYYY...",
        "......YYYo....",
        ".....YYYo.....",
        "....YYYo......",
        "...YYYYYYYY...",
        ".....yYYYo....",
        "....yYYYo.....",
        "...yYYo.......",
        "..yYYo........",
        ".yYo..........",
        "yo............",
    ],
    # A four-pointed compass rose.
    "compass_rose": [
        "......P.......",
        ".....PPr......",
        ".....PPr......",
        "....xPPrx.....",
        ".SSSSxwxbbbb..",
        "SsSSSwwwSSSbb.",
        ".SSSSxwxbbbb..",
        "....xpprx.....",
        ".....ppr......",
        ".....ppr......",
        "......r.......",
    ],
}
