"""Generates BLOCKMANIA's card portraits: one original 16x16 pixel sprite per Joker, item and
Workshop tool, plus the achievement badge icons (original art, authored as code).

Run:  python tools/art/gen_cards.py
Out:  assets/ui/cards/<set>.png   one row per sprite, 8 frames of 16x16 art pixels:
                                    frame 0 = rest pose, frames 1-6 = a light glint sweeping
                                    across the sprite, frame 7 = silhouette (locked / unknown)
      assets/ui/cards/cards.json   {set: {id: row}}

Sprites are drawn as ASCII on a 14x14 canvas; the generator centers them in 16x16 and adds the
1-pixel ink outline, so every portrait shares one weight of line. Letters map to the UI kit
palette (tools/art/gen_ui.py ICON_PALETTE) plus a few extra ramps defined below.
Godot draws the sheets at whole-number scales with nearest filtering (BMCardArt).
"""
import json
import os
import sys
from PIL import Image

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen_ui import ICON_PALETTE, INK, CLEAR  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(ROOT, "assets", "ui", "cards")
CELL = 16
FRAMES = 8

PAL = dict(ICON_PALETTE)
PAL.update({
    "x": (214, 208, 226, 255), "X": (160, 152, 178, 255), "z": (120, 112, 138, 255), "Z": (78, 72, 98, 255),
    "n": (255, 162, 82, 255), "N": (224, 104, 30, 255),
    "i": (214, 176, 255, 255), "h": (160, 96, 250, 255), "H": (108, 54, 200, 255),
    "q": (206, 248, 255, 255), "Q": (120, 214, 240, 255), "j": (58, 150, 190, 255),
    "a": (255, 214, 178, 255), "A": (226, 160, 120, 255),
    "t": (44, 30, 60, 255),
    "f": (150, 120, 196, 255), "F": (108, 82, 150, 255),
})

# Badge frames for achievements, 24x24 art pixels: rim ramps (light, mid, dark, deepest).
BADGE = 24
BADGE_TIERS = {
    "bronze": ((255, 196, 140, 255), (214, 128, 72, 255), (158, 82, 44, 255), (96, 46, 28, 255)),
    "silver": ((244, 244, 255, 255), (184, 188, 214, 255), (124, 126, 160, 255), (74, 72, 104, 255)),
    "gold": ((255, 246, 176, 255), (255, 204, 61, 255), (222, 150, 34, 255), (140, 84, 18, 255)),
    "legend": ((255, 214, 255, 255), (214, 120, 255, 255), (140, 70, 220, 255), (70, 34, 130, 255)),
    "locked": ((110, 100, 130, 255), (78, 70, 100, 255), (58, 50, 78, 255), (36, 28, 52, 255)),
    "secret": ((92, 66, 130, 255), (63, 43, 94, 255), (45, 30, 67, 255), (26, 16, 38, 255)),
}

# ------------------------------------------------------------------------------ Jokers
JOKERS = {
    "clean_sweep": [
        "...........ed.",
        "..........ed..",
        ".........ed...",
        "........ed....",
        ".......ed.....",
        "......PPr.....",
        ".....PPrr.....",
        "....yYYYYo....",
        "...yYYYYYoo...",
        "..yYoYoYoYo...",
        "..YoYoYoYoO...",
        "..Yo.Yo.Yo....",
        "..............",
        "cc.c.cC.c..C..",
    ],
    "crossbar": [
        "......sS......",
        "......Sb......",
        "......sS......",
        "......Sb......",
        "......sS......",
        "......Sb......",
        "pPpPpPwwpPpPpP",
        "PrPrPrwwPrPrPr",
        "......sS......",
        "......Sb......",
        "......sS......",
        "......Sb......",
        "......sS......",
        "......Sb......",
    ],
    "small_change": [
        "..............",
        "..........yYo.",
        "..........oOO.",
        "......yYo.yYo.",
        "......oOO.oOO.",
        "......yYo.yYo.",
        "..yYo.oOO.oOO.",
        "..oOO.yYo.yYo.",
        "..yYo.oOO.oOO.",
        "..oOO.yYo.yYo.",
        "..yYo.oOO.oOO.",
        "..oOO.yYo.yYo.",
        ".CCCCCCCCCCCC.",
        "..............",
    ],
    "heavy_hand": [
        "....zzzzzz....",
        "...zXXXXXXz...",
        "..zXz....zXz..",
        "..zXz....zXz..",
        "..zXz....zXz..",
        "...zXXXXXXz...",
        "..ZXXxxXXXXZ..",
        ".ZXxxXXXXXXXZ.",
        ".ZXxXXPPPXXXZ.",
        ".ZXXXXPXXXXXZ.",
        ".ZXXXXPPPXXXZ.",
        ".ZXXXXXXPXXZZ.",
        "..ZXXXPPPXZZ..",
        "...ZZZZZZZZ...",
    ],
    "first_strike": [
        "........yyYY..",
        ".......yYYYo..",
        "......yYYYo...",
        ".....yYYYo....",
        "....yYYYo.....",
        "...yYYYYYYYo..",
        "..yyyyYYYYo...",
        "......yYYo....",
        ".....yYYo.....",
        "....yYYo......",
        "...yYo........",
        "..yYo...p..p..",
        ".yo....pPppPp.",
        "........pPPp..",
    ],
    "neat_freak": [
        "...w.......w..",
        "..www..s..www.",
        "...w..sw...w..",
        "......s.......",
        "...kkkkk......",
        "..MMMMMMkkk...",
        "..mMMMMMgggk..",
        "...kMgk....k..",
        "..mmMMMg......",
        ".mMMMMMMg.....",
        ".mMwMMMMg.....",
        ".mMwMMMMg.....",
        ".mMMMMMMg.....",
        "..gggggg......",
    ],
    "corner_office": [
        "cccccccccccccc",
        "cCCCCCCCCCCCCC",
        "cC............",
        "cC....mM......",
        "cC...mMgM.....",
        "cC..mMgMMg....",
        "cC...gMgg.....",
        "cC....gd......",
        "cC..EEEEEE....",
        "cC..eEEEEd....",
        "cC...EEEd.....",
        "cC...EEEd.....",
        "cC....dd......",
        "cC............",
    ],
    "blue_mood": [
        "..............",
        ".....sss......",
        "...ssSSSss....",
        "..sSSSSSSSs...",
        ".sSSwSSSSSSs..",
        ".SSSSSSSSSSSb.",
        "sSSSSSSSSSSSSb",
        ".bbSSSSSSSSbb.",
        "...bbbbbbbb...",
        "..s...s...s...",
        ".s...s...s....",
        "...s...s...s..",
        "..s...s...s...",
        "..............",
    ],
    "chain_link": [
        "..............",
        "..xxxx........",
        ".xX..Xx.......",
        ".x....X.......",
        ".x..xxxxx.....",
        ".xX.X.XxX.....",
        "..xxXx..Xx....",
        "....x..xxxxx..",
        "....Xx.X.XxXz.",
        ".....XXXxX..X.",
        ".......z....X.",
        ".......zX..Xz.",
        "........zzzz..",
        "..............",
    ],
    "spare_parts": [
        ".....kX.......",
        "..Xk.XXX.kX...",
        "..XXXXXXXXX...",
        "...XXzzzXXz...",
        ".XXXzt.tzXXX..",
        ".XXXz...zXXz..",
        "...XztttzXz...",
        "..XXXzzzXXX...",
        "..XX.XXz.XZ...",
        ".......Z..yyYY",
        "..........Yo..",
        "..........Yo..",
        "..........Yo..",
        "..........oO..",
    ],
    "tiny_insurance": [
        "..............",
        "......P.......",
        "....PPPPP.....",
        "..PpPPPPPPr...",
        ".PpPPpPPPPrr..",
        "PpPPpPPPPPPrr.",
        "PPPrrPPrrPPrr.",
        "r..r..Y..r..r.",
        "......Y.......",
        "......Y.......",
        "......Y.......",
        "......Y..Y....",
        ".......YY.....",
        "..............",
    ],
    "second_look": [
        "....kkkkk.....",
        "...kssssbk....",
        "..ksccccCbk...",
        ".kscccccccbk..",
        ".kscckkkcCbk..",
        ".ksckSSSkCbk..",
        ".ksckSwSkCbk..",
        ".kscckkkcCbk..",
        "..kbcccccbk...",
        "...kbbbbbkEE..",
        "....kkkkkEEd..",
        "..........EEd.",
        "...........Edd",
        "............dd",
    ],
    "wide_awake": [
        "....c..c......",
        "...c..c..c....",
        "....c..c..c...",
        "...c..c..c....",
        "..............",
        "..cccccccccc..",
        "..cCDDDDDDCcCC",
        "..cCCCCCCCCc.C",
        "..cCPPPPPPCc.C",
        "..cCPpPPrPCcCC",
        "..cCPPPPPPCc..",
        "..ccCCCCCCcc..",
        "...cccccccc...",
        "..CCCCCCCCCCC.",
    ],
    "hollow_point": [
        "....pPPPPp....",
        "..ppPwPPPPPp..",
        ".pPPPPPPwPPPr.",
        ".PPwPPeeePPPr.",
        "pPPPPeEEEePwPr",
        "PPPPeE....ePPr",
        "PPwPE.....EPPr",
        "PPPPE.....EPwr",
        "PPPPeE...EePPr",
        "rPPPPeEEEePPrr",
        ".rPwPPEEEPPPr.",
        ".rrPPPPwPPPrr.",
        "..rrrPPPPrrr..",
        "....rrrrrr....",
    ],
    "pressure_cooker": [
        "....c....c....",
        "...c..c...c...",
        "....c..c.c....",
        "......kk......",
        "...kkkXXkkk...",
        "..kxxxxxxxXk..",
        "XXXXXXXXXXXXXX",
        "zXxxxxxxxxxXzz",
        ".zxXXXXXXXXxz.",
        ".zxXX.PP.XXxz.",
        ".zxX.p.P..XXz.",
        ".zxXX.kk.XXXz.",
        ".zXXXXXXXXXXz.",
        "..zzzzzzzzzz..",
    ],
    "golden_ratio": [
        "..............",
        "....yYYYYYo...",
        "...yY.....oO..",
        "..yY.......o..",
        ".yY..yYYYo..o.",
        ".Y..yY....o.O.",
        ".Y..Y..yYo.oO.",
        ".Y..Y..Y.o.O..",
        ".Y..o...Oo.O..",
        ".Yo..o.....O..",
        "..Yo..ooooO...",
        "...Yo.........",
        "....YYoo......",
        "..............",
    ],
    "color_cycle": [
        "....PPPPnn....",
        "..PPPPPPnnnn..",
        ".PPPPPPPnnnnn.",
        ".PPPPPPPnnnnY.",
        "hPPPPPPnnnYYYY",
        "hhhhhhwwYYYYYY",
        "hhhhhhwwYYYYYY",
        "hhhhSSSMMMYYYY",
        "hhSSSSSMMMMMYY",
        ".SSSSSSMMMMMM.",
        ".SSSSSSMMMMMM.",
        "..SSSSSMMMMM..",
        "....SSSMMM....",
        "..............",
    ],
    "patch_panel": [
        "..............",
        ".........AAA..",
        "........AaaaA.",
        ".......AaaaaaA",
        "......AaacacaA",
        ".....AaaaaaaA.",
        "....AaacacaA..",
        "...AaaaaaaA...",
        "..AaacacaA....",
        ".AaaaaaaA.....",
        "Aaaaaaa.A.....",
        "AaaaaA........",
        ".AAAA.........",
        "..............",
    ],
    "long_game": [
        ".EEEEEEEEEEEE.",
        ".dddddddddddd.",
        "..q........Q..",
        "..qQ......QQ..",
        "...qyYYYYoQ...",
        "....qYYYoQ....",
        ".....qYoQ.....",
        ".....qYoQ.....",
        "....q..oQQ....",
        "...q...Y..Q...",
        "..q...yYo..Q..",
        "..qyYYYYYYoQ..",
        ".EEEEEEEEEEEE.",
        ".dddddddddddd.",
    ],
    "fire_sale": [
        "......P...P...",
        ".....PYP.PYP.P",
        "....PYyYPYyYPY",
        ".....yyYYyyYy.",
        "....cccccccccC",
        "...cccPcckcccC",
        "..cxcccckccccC",
        "..cxccckcccccC",
        "...ccckccPcccC",
        "....cccccccccC",
        "....CCCCCCCCCC",
        "..............",
        "..............",
        "..............",
    ],
    "jackpot_window": [
        "............Pp",
        ".PPPPPPPPPP.PP",
        "PpyyYYYYYYyP.X",
        "PkkkkkkkkkkrX.",
        "PkcckccKcckrX.".replace("K", "k"),
        "PkcPkcPkcPkrX.",
        "PkcPkcPkcPkrX.",
        "PkcckccKcckrX.".replace("K", "k"),
        "PkkkkkkkkkkrX.",
        "PPPPPPPPPPrrX.",
        "PoooPYYPoooPX.",
        "PrrrrrrrrrrrXX",
        "PrPrPrPrPrPr..",
        ".RRRRRRRRRRR..",
    ],
    "mirror_maze": [
        "....yYYYYo....",
        "...yqqqqqqo...",
        "..yqwqqqqQQo..",
        "..YqqwqqqQQo..",
        "..YqqqqqQQjo..",
        "..YqqqqQQQjo..",
        "..YqqqQQQjjo..",
        "...oQQQjjjo...",
        "....ooooooO...",
        "......Yo......",
        "......Yo......",
        "......Yo......",
        ".....yYoO.....",
        "......oO......",
    ],
    "compound_interest": [
        "...........MM.",
        "..........MMM.",
        ".........MgMg.",
        "........Mg..g.",
        "..pppp.Mg.....",
        ".pPPPPpg......",
        "pPPkPPPPr.....",
        "pPPPPPPPPrPP..",
        "PPPPPPPPPrrr..",
        "rPPPPPPPPr....",
        ".rPPPPPPr.....",
        "..rr..rr......",
        "..rr..rr......",
        "..............",
    ],
    "last_stand": [
        ".SSSSSSSSSSSS.",
        ".SssssSSSSSSb.",
        ".SsSSSkSSSSSb.",
        ".SsSSkkSSSSSb.",
        ".SSSkkkkSSSSb.",
        ".SSSSkkSSSSSb.",
        ".SSSSSkSSSSSb.",
        "..SSSSSkSSSb..",
        "..SSSSSSkSSb..",
        "...SSSSSkSb...",
        "....SSSSkb....",
        ".....SSSb.....",
        "......Sb......",
        "..............",
    ],
    "hoarder": [
        ".....yYyo.....",
        "...yYoYyYo....",
        "..oYyoYoyYO...",
        "..kCCCCCCCk...",
        "...kcCCCCk....",
        "....kCCCk.....",
        "...kcccccCk...",
        "..kccccccCCk..",
        ".kcccccccCCCk.",
        ".kccccccccCCk.",
        ".kcccccccCCCk.",
        ".kcccccccCCCk.",
        "..kCCCCCCCCk..",
        "...kkkkkkkk...",
    ],
    "architect": [
        "......kk......",
        "......YY......",
        ".....kYok.....",
        ".....X..X.....",
        "....X....X....",
        "....X....X....",
        "...X......X...",
        "...X......X...",
        "..X........X..",
        "..X........X..",
        ".X..........X.",
        "SSSSSSSSSSSSSb",
        "SbSbSbSbSbSbSb",
        "..............",
    ],
    "straight_edge": [
        "..............",
        "..............",
        "yYYYYYYYYYYYYo",
        "YkYkYkYkYkYkYo",
        "Yk.k.k.k.k.kYo",
        "Yk...k...k..Yo",
        "YYYYYYYYYYYYYo",
        "oooooooooooooO",
        "..............",
        ".sSSsSSsSSsSS.",
        ".SSbSSbSSbSSb.",
        ".bbbbbbbbbbbb.",
        "..............",
        "..............",
    ],
    "square_deal": [
        "..............",
        "..ccccccccc...",
        ".cwwwwwwwwCC..",
        ".cwkkwwwkkCC..",
        ".cwkkwwwkkCC..",
        ".cwwwwwwwwCC..",
        ".cwwwkkwwwCC..",
        ".cwwwkkwwwCC..",
        ".cwwwwwwwwCC..",
        ".cwkkwwwkkCC..",
        ".cwkkwwwkkCC..",
        ".cwwwwwwwwCC..",
        "..CCCCCCCCC...",
        "..............",
    ],
    "last_piece": [
        "..............",
        "......yYo.....",
        ".....yYYYo....",
        ".....YYYYo....",
        "..yYYYYYYYYo..",
        "..YYYYYYYYYo..",
        "..YYYYYYYYYYYo",
        "....YYYYYYYYYo",
        "....YYYYYYYYoo",
        "...yYYYYYYYYO.",
        "..YYYYYYYYYo..",
        "..YYYYYYYYYo..",
        "..oooooooooO..",
        "..............",
    ],
    "postmaster": [
        "..............",
        "cccccccccccccc",
        "cCccccccccPPPC",
        "cCCccccccPpPrC",
        "cCcCccccCPPPrC",
        "cCccCccCcPrrrC",
        "cCcccCCcccccCC",
        "cCccccccccccCC",
        "cCcccccccccCCC",
        "cCCCCCCCCCCCCC",
        "..............",
        "..............",
        "..............",
        "..............",
    ],
    "lean_bag": [
        "..............",
        "..........lll.",
        "........llLLl.",
        "......llLLLl..",
        ".....lLLLLl...",
        "....lLLLLl....",
        "...lLLLLl.....",
        "...lLLLl......",
        "..lLLLl.......",
        "..lLLl........",
        "..lLl.........",
        ".lL...........",
        ".l............",
        "l.............",
    ],
    "foundry": [
        "....n...n.....",
        "...nYn.nYn....",
        "....yYYYYYo...",
        "....YyyYYYo...",
        "....oooooOO...",
        "..............",
        "zZZZZZZZZZZZ..",
        "XXxxxxxxxxxXZ.",
        ".ZXXXXXXXXXXXZ",
        "...ZXXXXXZZ...",
        "....ZXXXXZ....",
        "...ZXXXXXXZ...",
        "..ZZZZZZZZZZ..",
        "..............",
    ],
    "neon_sign": [
        "tttttttttttttt",
        "tUUUUUUUUUUUUt",
        "tU..pp..pp..Ut",
        "tU.pPPppPPp.Ut",
        "tU.pPwPPPPp.Ut",
        "tU.pPPPPPPp.Ut",
        "tU..pPPPPp..Ut",
        "tU...pPPp...Ut",
        "tU....pp....Ut",
        "tUUUUUUUUUUUUt",
        "tttttttttttttt",
        ".....z..z.....",
        "....zz..zz....",
        "..............",
    ],
    "specialist": [
        "......kk......",
        "....kkUUkk....",
        "..kkUUUUUUkk..",
        "kkUUUUUUUUUUkk",
        "..kkUUUUUUkkY.",
        "....kUUUUk..Y.",
        "...kUUUUUUk.Y.",
        "...kuuuuuuk.Y.",
        "....kkkkkk.yYo",
        "...........YYo",
        "............o.",
        "..............",
        "..............",
        "..............",
    ],
    "recycler": [
        "......M.......",
        ".....MmM......",
        "....MmgMM.....",
        "...Mg..gMM....",
        "..MM....gM....",
        ".MM......Mg...",
        "MMMM....MMMMM.",
        ".gM......gMg..",
        "..Mg......M...",
        "...MgggggMMg..",
        "..MMMMMMMMMMg.",
        "...gMg........",
        "....g.........",
        "..............",
    ],
    "glass_cannon": [
        "..............",
        ".........q..w.",
        "......qqqQQ.w.",
        "....qqwqQQQj..",
        "..qqwqqQQQj...",
        ".qwqqQQQQj....",
        ".qqQQQQQj.....",
        "..QQQQjj......",
        "...EEEEEE.....",
        "..EeeeeEEE....",
        ".EeEEEEEdEE...",
        ".EEdEEEEdEd...",
        "..EEd..EEd....",
        "...dd...dd....",
    ],
    "collector": [
        "eeeeeeeeeeeeee",
        "eEEEEEEEEEEEEd",
        "eEttttttttttEd",
        "eEt.p..P..p.Ed",
        "eEtpPp.P.pPpEd",
        "eEtpPPpkpPPpEd",
        "eEt.pPpkpPp.Ed",
        "eEt.pPpkpPp.Ed",
        "eEtpPp.k.pPpEd",
        "eEt.p..k..p.Ed",
        "eEt.........Ed",
        "eEttttttttttEd",
        "eEEEEEEEEEEEEd",
        "dddddddddddddd",
    ],
    "mimic": [
        "..............",
        "..eeeeeeeeee..",
        ".eEEEEEEEEEEd.",
        ".eEyYEEEEyYEd.",
        ".eEEEEEEEEEEd.",
        ".wkwkwkwkwkwk.",
        ".tttttttttttt.",
        ".tttPPPPPPttt.",
        ".ttPpPPPPPrtt.",
        ".kwkwkwkwkwkw.",
        ".eEEEyYoEEEEd.",
        ".eEEEEooEEEEd.",
        ".dddddddddddd.",
        "..............",
    ],
    "hot_hand": [
        "...P....P.....",
        "..PYP..PYP..P.",
        "..PyYPPYyYPPYP",
        "...yyYYyyYYyy.",
        "..cwwwkcwwwk..",
        "..cwPwkcwSwk..",
        "..cPPPkcSSSk..",
        "..cwPwkcwSwk..",
        "..cwwwkcwwwk..",
        "..cwwwkcwwwk..",
        "..CCCCkCCCCk..",
        "..............",
        "..............",
        "..............",
    ],
    "card_sharp": [
        "..............",
        "..cwwwk.......",
        "..cwPwk.......",
        "..cPPPkcwwwk..",
        "..cwPwkcwkwk..",
        "..cwwwkckkkk..",
        "..cwwwkcwkwk..",
        "..cwwwkcwwwk..",
        "..cwwPkcwwwk..",
        "..cCCCkcwwkk..",
        ".......cCCCk..",
        "..............",
        ".XXXXXXXXXXXX.",
        "..............",
    ],
    "patience": [
        "..............",
        "..............",
        "...z.z........",
        "...z.z........",
        "...xxx........",
        "...xkx..eeee..",
        "...xxx.eEdddE.",
        "...xxx.EdeeedE",
        "...xxxxEdEdEdE",
        "...xxxxEdeedEE",
        "..xxxxxxEEEEEx",
        ".xxxxxxxxxxxx.",
        "..XXXXXXXXXX..",
        "..............",
    ],
    "locksmith": [
        "..yYYo........",
        ".yY..Yo.......",
        ".Y....o.......",
        ".Y....o.......",
        ".oY..oO.......",
        "..oYYO........",
        "...Yo.........",
        "...Yo.........",
        "...YoYo.......",
        "...Yo.........",
        "...YoYYo......",
        "...Yo.........",
        "...YYo........",
        "....o.........",
    ],
    "countdown": [
        ".........y..y.",
        "........Y.yY..",
        ".......n..Y...",
        "......n.......",
        "....zzXz......",
        "..ZZZZZZZZ....",
        ".ZZzZZZZZZZ...",
        "ZZzZZyYYZZZZ..",
        "ZZZZZZZYZZZZ..",
        "ZZZZZZYYZZZZ..",
        "ZZZZZZZYZZZZ..",
        ".ZZZZyYYZZZ...",
        "..ZZZZZZZZ....",
        "....ZZZZ......",
    ],
    "breakage_bonus": [
        "......q.......",
        "..q..qQ...q...",
        "..qQ.qQj.qQ...",
        "...Qj.Qj.Q....",
        ".q............",
        ".qQ...qqq..qq.",
        "..Q..qQQj..Qj.",
        ".....Qj.......",
        "....yYYYYo....",
        "...yYoYYYYo...",
        "...YYoYYYYo...",
        "...YYYOOOYo...",
        "....oooooo....",
        "..............",
    ],
    "insurance_policy": [
        ".cccccccccc...",
        ".cCCCCCCCCcC..",
        ".cckkkkkkkcC..",
        ".cccccccccCC..",
        ".cckkkkkkcCC..",
        ".cccccccccCC..",
        ".cckkkkkcMMM..",
        ".ccccccccMmMM.",
        ".cckkkkcMMmMMg",
        ".ccccccccMMMg.",
        ".cccccccMgMgM.",
        ".CCCCCCCM..gM.",
        "..............",
        "..............",
    ],
    "showboat": [
        "Y.............",
        ".....tttt...y.",
        "....tUUUUt..Y.",
        "....tUUUUt.yYo",
        "....tUUUUt..Y.",
        "....tUUUUt....",
        "....PPPPPP....",
        "....tUUUUt....",
        "..ttttttttttt.",
        "..tUUUUUUUUUt.",
        "...ttttttttt..",
        "..........Y...",
        ".Y.......yYo..",
        "..........Y...",
    ],
    "full_tank": [
        "..........XX..",
        ".........XX...",
        "..kkkk..XX....",
        ".kPPPPPPPPr...",
        "kPkkkPPPPPPr..",
        "kPPPPPPPPPPr..",
        "kPpPPPPPPPrr..",
        "kPpPkPPPkPrr..",
        "kPpPPkPkPPrr..",
        "kPpPPPkPPPrr..",
        "kPpPPkPkPPrr..",
        "kPpPkPPPkPrr..",
        "kPPPPPPPPPrr..",
        ".rrrrrrrrrr...",
    ],
    "overflow": [
        "...ss..s......",
        "..s..s...s....",
        "..SSSSSSSSSS..",
        "..qSSsSSSSSQs.",
        "s.qSSSSSSSSQ.s",
        "..qSSSSSSSSQ..",
        "S.qqSSSSSSQQ.S",
        "...qSSSSSSQ...",
        "...qqSSSSQQ..S",
        "S...qSSSSQ....",
        "....qqQQQQ....",
        "......qQ......",
        "....qqqQQQ....",
        ".SSSSSSSSSSSb.",
    ],
    "keystone": [
        "....yYYYYo....",
        ".XX.YYYYYo.XX.",
        "XxX.oYYYO..XzX",
        "XxXX.oYO..XXzX",
        "XxxXX....XXzzX",
        "XxxX......XzzX",
        "XxX........zzX",
        "XxX........XzX",
        "XxX........XzX",
        "XxX........XzX",
        "XxX........XzX",
        "XxX........XzX",
        "ZZZZ......ZZZZ",
        "..............",
    ],
    "draftsman": [
        "...........pP.",
        "..........pPr.",
        ".........XXz..",
        "........YYo...",
        ".......YYo....",
        "......YYo.....",
        ".....YYo......",
        "....YYo.......",
        "...YYo........",
        "..aAA.........",
        "..AA..........",
        "..t...........",
        "..SSSSSSSS....",
        "..............",
    ],
    "periscope": [
        "......kkkkk...",
        ".....XqQjzX...",
        ".....XQjzzX...",
        ".....XXXXXX...",
        ".....XXz......",
        ".....XXz......",
        ".....XXz......",
        ".....XXz......",
        "sSSSSSSSSSSSSb",
        "SbSSSbSSSSSbSb",
        "bbbbbbbbbbbbbb",
        "..............",
        "..............",
        "..............",
    ],
    "loan_shark": [
        "..............",
        "......XX......",
        ".....XXX......",
        "....XXXX......",
        "...XXXXX......",
        "..XxXXXXX.....",
        ".XxxXXXXXX....",
        "XxxxXXXXXXX...",
        "SSSSSSSSSSSSSS",
        "SsSSSbSSSbSSsS",
        "bbbbbbbbbbbbbb",
        "..........yYo.",
        ".........yYoYo",
        "..........oOO.",
    ],
}

# ------------------------------------------------------------------------------ Items
ITEMS = {
    "polish": [
        "......w.......",
        ".....www......",
        "......w...w...",
        "...kkkk..www..",
        "...kXXk...w...",
        "..kkkkkk......",
        ".mMMMMMMg.....",
        ".mMwMMMMg.....",
        ".mMwMMMMg.....",
        ".mMMmmMMg.....",
        ".mMMMMMMg.....",
        ".mMMMMMMg.....",
        ".ggggggggg....",
        "..............",
    ],
    "spark": [
        "......y.......",
        "...y..Y..y....",
        "....Y.Y.Y.....",
        ".....yYy......",
        ".yYYYwwwYYYy..",
        ".....yYy......",
        "....Y.Y.Y.....",
        "...y..YX.y....",
        "......XX......",
        ".....XX.......",
        "....XX........",
        "...XX.........",
        "..XX..........",
        "..............",
    ],
    "eraser": [
        "..............",
        "......pppPP...",
        ".....pPPPPPr..",
        "....pPPPPPrr..",
        "...pPPPPPrrR..",
        "..ssssSPPrR...",
        ".sSSSSbPrR....",
        "sSSSSbbrR.....",
        "SSSSbbR.......",
        ".bbbbR........",
        "..............",
        "..C..C.C......",
        ".C.CC....C....",
        "..............",
    ],
    "second_tray": [
        "..............",
        "...LLLLLLLLLL.",
        "..LlllllllllLu",
        "..LUUUUUUUUULu",
        "..............",
        ".LLLLLLLLLLL..",
        "LlPPlYYlSSlLu.",
        "LlPrlYolSblLu.",
        "LUUUUUUUUUULu.",
        ".uuuuuuuuuuu..",
        "..............",
        ".....MM.......",
        "....MMMM......",
        "...M.MM.M.....",
    ],
    "extra_turn": [
        "....kkkkkk....",
        "..kkccccccCk..",
        ".kccccPcccCCk.",
        ".kcccccccccCk.",
        "kccccckccccCCk",
        "kcPccckccccPCk",
        "kccccckkkccCCk",
        "kcccccccccCCCk",
        ".kcccccccCCCk.",
        ".kCccPcccCCk..",
        "..kkCCCCCkkMM.",
        "....kkkkk.MMMM",
        "............MM",
        "..............",
    ],
    "lucky_paint": [
        ".......MM.....",
        "......MmgM....",
        ".....MMmMMM...",
        "......MgMg....",
        ".kkkkkkkkkkk..",
        "kxxxxxxxxxxXk.",
        "kPPPPPPPPPPPk.",
        "kPpPPPPPPPPrk.",
        "kxXXXXXXXXXzk.",
        "kxXXXXXXXXXzk.",
        "kxXXXXXXXXXzk.",
        "kxXXXXXXXXXzk.",
        ".kzzzzzzzzzk..",
        "..............",
    ],
    "blueprint": [
        "..............",
        ".sSSSSSSSSSSb.",
        "sSwwwwSSwwwSbb",
        "sSwSSwSSwSwSbb",
        "sSwSSwwwwSwSbb",
        "sSwSSSSSSSwSbb",
        "sSwwwwwwwwwSbb",
        "sSSSSSSSSSSSbb",
        ".bbbbbbbbbbbbB",
        "............bB",
        "..............",
        "..............",
        "..............",
        "..............",
    ],
    "cash_out": [
        "..............",
        "...MMMMMMMMM..",
        "..MmmmmmmmmMg.",
        "..MmgggggmmMg.",
        ".MMMMMMMMMMMMg",
        "MmmmmmmmmmmmMg",
        "MmMgMMyYMMgmMg",
        "MmgMMyYoYMMgMg",
        "MmMgMMoOMMgmMg",
        "MmmmmmmmmmmmMg",
        ".gggggggggggg.",
        "..............",
        "..............",
        "..............",
    ],
    "punch": [
        "..............",
        "....PPPPPP....",
        "..PPpppPPPPr..",
        ".PpPPPPPPPPrr.",
        ".PpPPPPPPPPrr.",
        "PpPPPPPPPPPPrr",
        "PpPPrPPPPPPPrr",
        "PPPPPrPPPPPPrr",
        ".PPPPPrrPPPrr.",
        "..PPPPPPPPrr..",
        "...rrrrrrrr...",
        "...cccccccC...",
        "...cCCCCCCC...",
        "...ccccccCC...",
    ],
    "color_purge": [
        "......kkk.....",
        ".....kXXXk....",
        ".....XXXXX....",
        "....xXXXXXz...",
        "...xXXXXXXXz..",
        "...xPnYMShXz..",
        "...xPnYMShXz..",
        "...xXXXXXXXz..",
        "...xXXXXXXXz..",
        "...xXXXXXXXz..",
        "...zzzzzzzzz..",
        "..............",
        "..............",
        "..............",
    ],
    "emergency_brick": [
        "......PP......",
        ".....PppP.....",
        "..y..PPPr..y..",
        "...y.rrrr.y...",
        "..............",
        "kkkkkkkkkkkkkk",
        "kppPPkpPPPPPrk",
        "kPPPrkPPPPPrrk",
        "kkkkkkkkkkkkkk",
        "kPPrkpPPPPrkPk",
        "krrrkPPPPrrkrk",
        "kkkkkkkkkkkkkk",
        "..............",
        "..............",
    ],
}

# ------------------------------------------------------------------------------ Workshop tools
TOOLS = {
    "copier": [
        "....cccccc....",
        "...cCCCCCCc...",
        ".XXXXXXXXXXXX.",
        "XxxxxxxxxxxxxZ",
        "XxMMXXXXXXPxxZ",
        "XxxxxxxxxxxxxZ",
        "XXXXXXXXXXXXXZ",
        "XzzzzzzzzzzzzZ",
        ".ZcccccccccZ..",
        "..cSSccSScC...",
        "..cSSccSScC...",
        "..cccccccCC...",
        "..............",
        "..............",
    ],
    "shredder": [
        "..cccccccc....",
        "..cCPPcccC....",
        "..cCPPccCC....",
        "XXXXXXXXXXXXX.",
        "XxxxxxxxxxxxXZ",
        "XxxPxxxxxxxxXZ",
        "XXXXXXXXXXXXXZ",
        "ZZZZZZZZZZZZZZ",
        "..c.C.P.c.C...",
        "..c.c.P.C.c...",
        "..C.c...c.C...",
        "....C...C.....",
        "..............",
        "..............",
    ],
    "turntable": [
        "EEEEEEEEEEEEEE",
        "EeeeeeeeeeeeEd",
        "Ee..tttt...XEd",
        "Ee.tUUUUt..XEd",
        "EetUUPPUUt.XEd",
        "EetUPpPPUtX.Ed",
        "EetUPPrPUXX.Ed",
        "EetUUPPUUt..Ed",
        "Ee.tUUUUt...Ed",
        "Ee..tttt....Ed",
        "EeeeeeeeeeeeEd",
        "dddddddddddddd",
        "..............",
        "..............",
    ],
    "repaint": [
        ".PPPPPPPPPPP..",
        "PpPPPPPPPPPPr.",
        "PpPPPPPPPPPrrX",
        ".rrrrrrrrrrr.X",
        ".............X",
        ".......XXXXXXX",
        ".......X......",
        ".......X......",
        "......ZZZ.....",
        "......ZzZ.....",
        "......ZzZ.....",
        "......ZzZ.....",
        "......ZZZ.....",
        "..............",
    ],
    "schematic": [
        "...X..........",
        "..XzX.........",
        "..XzX.........",
        "..XXX.........",
        ".X...X........",
        ".X....X.......",
        "X......X......",
        "sSSSSSSSSSSSb.",
        "sSwwSwwSwwwSb.",
        "sSwSSSwSSSwSb.",
        "sSwwwwwSwwwSb.",
        "sSSSSSSSSSSSb.",
        ".bbbbbbbbbbb..",
        "..............",
    ],
}

# ------------------------------------------------------------------------------ Achievement icons
# Each is drawn inside a tiered badge frame in Godot (BMTrophyCase).
ACHIEVEMENTS = {
    "first_line": [
        "..............",
        "...w.....w....",
        "..www...www...",
        "...w.....w....",
        "..............",
        "PPnnYYMMSShhPP",
        "pPnNyYmMsShHpP",
        "PrNNYoMgSbHHPr",
        "..............",
        "..c..c...C..c.",
        ".c.C...c...C..",
        "..............",
        "..............",
        "..............",
    ],
    "first_round": [
        "............Ed",
        "....PPPPP..Ed.",
        "..PPcccccPEd..",
        ".PccPPPPPEdP..",
        ".PcPPcccEdcP..",
        "PcPPccPEdPcPP.",
        "PcPcPPYYPcPcP.",
        "PcPcPPYYPcPcP.",
        "PcPPcPPPPcPcP.",
        ".PcPPcccccPP..",
        ".PccPPPPPPcP..",
        "..PPcccccPP...",
        "....PPPPP.....",
        "..............",
    ],
    "boss_buster": [
        "...cccccccc...",
        "..ccccccccCC..",
        ".ccccccccccCC.",
        ".ccttcccttcCC.",
        ".cctttcttttCC.",
        ".ccttccctt.CC.",
        ".cccccttccCC..",
        "..cccc..ccCC..",
        "...ctcc.tcC...",
        "...ccctc.cC...",
        "....CCCCCCC...",
        "..............",
        "..y....y...y..",
        "...y..y.y.y...",
    ],
    "second_act": [
        "PPPPPPPPPPPPPP",
        "rPrPrPrPrPrPrP",
        "PPr........rPP",
        "PPr..yYYo..rPP",
        "PPr.....Yo.rPP",
        "PPr....Yo..rPP",
        "PPr...Yo...rPP",
        "PPr..yYYYo.rPP",
        "PPr........rPP",
        "Pr..........rP",
        "r............r",
        "EEEEEEEEEEEEEE",
        "dddddddddddddd",
        "..............",
    ],
    "final_act": [
        "PPPPPPPPPPPPPP",
        "rPrPrPrPrPrPrP",
        "PPr........rPP",
        "PPr..yYYo..rPP",
        "PPr.....Yo.rPP",
        "PPr...yYo..rPP",
        "PPr.....Yo.rPP",
        "PPr..yYYo..rPP",
        "PPr........rPP",
        "Pr..........rP",
        "r............r",
        "EEEEEEEEEEEEEE",
        "dddddddddddddd",
        "..............",
    ],
    "speedrunner": [
        "..............",
        "..............",
        "......SSSS....",
        ".....SsSSSS...",
        "c...SSSwSwSS..",
        "..c.SSSSSSSSS.",
        "c...SSSSSSSSSS",
        "..cSSSSSSSSSSS",
        "c.cwwwwwwwwwwc",
        "...CCCCCCCCCC.",
        "..............",
        "..............",
        "..............",
        "..............",
    ],
    "champion": [
        "...y..Y..y....",
        "...YyyYyyY....",
        "...YYYYYYY....",
        ".yyyyyyyyyYo..",
        "YoyYYYYYYYoYo.",
        "Y.oYYwYYYYo.Y.",
        "Yo.YYwYYYYo.Y.",
        ".YoYYYYYYYoYo.",
        "...oYYYYYo....",
        ".....YYo......",
        ".....YYo......",
        "...yYYYYYo....",
        "..EEEEEEEEEd..",
        "..dddddddddd..",
    ],
    "kit_winner": [
        "..............",
        ".....kkkk.....",
        "....k....k....",
        ".PPPPPPPPPPPP.",
        "PpPPPPPPPPPPPr",
        "PPPPPPPPPPPPPr",
        "rrrrrryYrrrrrr",
        "PPPPPPYoPPPPPr",
        "PpPPPPPPPPPPPr",
        "PpPPPPPPPPPPPr",
        "PPPPPPPPPPPPPr",
        ".rrrrrrrrrrrr.",
        "..............",
        "..............",
    ],
    "overtime": [
        "..YY......YY..",
        ".YyYo....YyYo.",
        ".YYo.kkkk.YYo.",
        "...kccccccK...".replace("K", "k"),
        "..kcccPcccCk..",
        ".kccccPccccCk.",
        ".kccccPccccCk.",
        ".kccccPPPccCk.",
        ".kcccccccccCk.",
        ".kcccccccccCk.",
        "..kcccccccCk..",
        "...kkkkkkkk...",
        "..kk......kk..",
        "..............",
    ],
    "sudden_death": [
        "......XX......",
        ".....XzzX.....",
        "...kkkkkkkk...",
        "..kccccccccC..",
        ".kcckkcckkcCk.",
        ".kcckkcckkcCk.",
        ".kccccccccccC.",
        ".kccccktcccCk.",
        ".kcccccccccCk.",
        "..kckckckckC..",
        "...kCCCCCCk...",
        "....kkkkkk....",
        "..............",
        "..............",
    ],
    "no_off_switch": [
        "......kk......",
        "..y...PP...y..",
        "...y..PP..y...",
        ".....PPPP.....",
        "..PP.PPPP.PP..",
        ".PP..PPPP..PP.",
        ".P....PP....P.",
        "PP..........PP",
        "PP..........PP",
        ".P..........P.",
        ".PP........PP.",
        "..PPP....PPP..",
        "....PPPPPP....",
        "..............",
    ],
    "broke_machine": [
        "..c...c.......",
        ".c.c.c.c..y.Y.",
        "..PPPPPPPPP.y.",
        ".PpPPPPPPPPrY.",
        ".PttttttttPr..",
        ".PtPtyStMtPr..",
        ".PttPtttStPr..",
        ".PttttYtttPr..",
        ".PPPPPPPPPPr..",
        ".PzzPXPzzPPr..",
        ".PPPPPPPPPPr..",
        ".PrPPPPPPrPr..",
        ".PPPPPPPPPPr..",
        ".rrrrrrrrrrr..",
    ],
    "blue_period": [
        "..............",
        "....ccccccc...",
        "..cccccccccCC.",
        ".ccSSccccccCC.",
        ".cSSSccbbccCCC",
        "cccSccbBBbcCCC",
        "cccccccbbccCC.",
        "ccsscccccccC..",
        "csSSsccc......",
        "cSSSScccc.....",
        ".cSSccccccCC..",
        "..ccccccccCC..",
        "....CCCCCC....",
        "..............",
    ],
    "square_dance": [
        "......X.......",
        "......X.......",
        "....sSSSb.....",
        "...SwSSSSb....",
        "..SSSSbSSSb...",
        "..SSSbSSSbSb..",
        "..SbSSSbSSSb..",
        "..SSSbSSSbSb..",
        "...SSSSbSSb...",
        "....bbbbbb....",
        "..............",
        ".w.........w..",
        "www...w...www.",
        ".w...www...w..",
    ],
    "full_spectrum": [
        "..............",
        "....PPPPPP....",
        "..PPnnnnnnPP..",
        ".PnnYYYYYYnnP.",
        ".PnYYMMMMYYnP.",
        "PnYMMSSSSMMYnP",
        "PnYMSShhSSMYnP",
        "PnYMShh..hSMYn",
        "PnYMSh....hSMY",
        "PnYMSh....hSMY",
        "..............",
        "..cc......cc..",
        ".ccccc..ccccc.",
        "..............",
    ],
    "packrat": [
        "..............",
        "..........cC..",
        "...XX....cccC.",
        "..XpXXXXXccCC.",
        "..XXXXXXXXcC..",
        ".XtXXXXXXXX...",
        "pXXXXXXXXXXX..",
        ".XXXxxxXXXXX..",
        "..XXXXXXXXXX..",
        "...X.X..X.X.p.",
        "............p.",
        "...........p..",
        "..............",
        "..............",
    ],
    "travel_light": [
        "..............",
        ".....XXXX.....",
        ".....X..X.....",
        "..EEEEEEEEEE..",
        ".EeeeeeeeeeEd.",
        ".EeEEEEEEEeEd.",
        ".EeEyYEEEEeEd.",
        ".EeEEEEEEEeEd.",
        ".EeeeeeeeeeEd.",
        ".EEEEEEEEEEEd.",
        "..dd.....dd...",
        "..............",
        "..............",
        "..............",
    ],
    "alchemist": [
        "...q..q.......",
        "....q...q.....",
        ".....kkkk.....",
        ".....XqQX.....",
        ".....qqQj.....",
        ".....qqQj.....",
        "....qqqQQj....",
        "...qqhhhhQj...",
        "..qqhihhhhQj..",
        ".qqhihhHhhhQj.",
        ".qhhhhhhhhhHj.",
        ".qhhhHhhhhHHj.",
        "..jjjjjjjjjj..",
        "..............",
    ],
    "special_delivery": [
        "..............",
        "...eeeeeeeee..",
        "..eEEEEyEEEEd.",
        ".eEEEEEyEEEdd.",
        "eeeeeeeyeeedd.",
        "eEPPEEEyEsSdd.",
        "eEPpEEEyEsbdd.",
        "eEEEEEEyEEEdd.",
        "eEMMEEEyEhhdd.",
        "eEMgEEEyEhHd..",
        "eEEEEEEyEEEd..",
        "ddddddddddd...",
        "..............",
        "..............",
    ],
    "full_house": [
        "......PP......",
        ".....PppP.....",
        "....PPPPrP....",
        "...PPPPPPrP...",
        "..PPPPPPPPrP..",
        ".PPPPPPPPPPrP.",
        "..cccccccccC..",
        "..cyYcyYcyYC..",
        "..cYocYocYoC..",
        "..cccccccccC..",
        "..cyYceecyYC..",
        "..cYoceEcYoC..",
        "..cccceEccCC..",
        "..............",
    ],
    "rare_taste": [
        "..............",
        "...sssSSSb....",
        "..swsSSSSbb...",
        ".sssSSSSSbbb..",
        "sSSSSSSSSSbbb.",
        ".SSSSSSSSbbb..",
        "..SSSSSSbbb...",
        "...SSSSbbb....",
        "....SSbbb.....",
        ".....Sbb......",
        "......b.......",
        "..............",
        ".y..........y.",
        "yYy........yYy",
    ],
    "master_plan": [
        "......YY......",
        "....yYYYYo....",
        "...yYwYYYYo...",
        "...YwYYYYYo...",
        "...YYYYYYYo...",
        "....YYYYYo....",
        ".....oYYo.....",
        ".....XXXX.....",
        ".....xXXz.....",
        ".....XXXX.....",
        "......zz......",
        "..y........y..",
        ".y..........y.",
        "..............",
    ],
    "piggy_bank": [
        "......kkk.....",
        ".......k......",
        "...pppppppp...",
        "..pPPPPPPPPp..",
        ".pPPkPPPPPPPpp",
        "pPPPPPPPPPPPPr",
        "pPPPPPPPPPPPPr",
        "rPPPPPPPPPPPr.",
        ".rPPPPPPPPPr..",
        "..rr.rr.rr....",
        "..rr.rr.rr....",
        "..............",
        "..............",
        "..............",
    ],
    "scrooge": [
        ".....DDDD.....",
        "......EE......",
        "....eEEEEd....",
        "...eEEyYEEd...",
        "..eEEyEEEEEd..",
        ".eEEEEyYEEEEd.",
        ".eEEEEEEyEEEd.",
        ".eEEEEyYEEEEd.",
        ".eEEEEEEEEEEd.",
        "..eddddddddd..",
        "yYo.yYo..yYo..",
        "oOO.oOOyYooOO.",
        "yYoyYoYoOyYo..",
        "oOOoOOoOO.oOO.",
    ],
    "big_hit": [
        "..............",
        "......Y.......",
        "..Y..YyY..Y...",
        "...YYyyyYY....",
        "..YyywwwyyY...",
        ".YyywPPPwyyY..",
        "YYyywPwPwyyYY.",
        ".YyywPPPwyyY..",
        "..YyywPwyyY...",
        "...YYywyYY....",
        "..Y..YyY..Y...",
        "......Y.......",
        "..............",
        "..............",
    ],
    "mega_hit": [
        "..n...Y....n..",
        "...n.YyY..n...",
        "Y...YyyyY....Y",
        ".YYYyywyyYYYY.",
        "..YyywwwwyyY..",
        "nYyywwPPwwyyYn",
        ".Yyyw1PPPwyyY.".replace("1", "P"),
        ".YyywwPPwwyyY.",
        "nYyyywwwwyyyYn",
        "..YyyyywyyyY..",
        ".YYYYyyyYYYYY.",
        "Y...YYyYY....Y",
        "...n..Y...n...",
        "..n.......n...",
    ],
    "giga_hit": [
        "............w.",
        "...........wq.",
        "..........qqj.",
        ".........qQj..",
        "........xXz...",
        ".......xXXz...",
        "......PxXz....",
        ".....PPXz.....",
        "....YnP.......",
        "...YnnY.......",
        "..YnY.........",
        ".Yn...........",
        "Y.............",
        "..............",
    ],
    "triple_decker": [
        "..............",
        "...eeeeeeee...",
        "..eEEEEEEEEd..",
        "..MMMMMMMMMM..",
        "..ddddddddd...",
        "..PPPPPPPPPP..",
        "..cCcCcCcCcC..",
        "..eEEEEEEEEd..",
        "..YYYYYYYYYY..",
        "..dddddddddd..",
        "..eEEEEEEEEd..",
        "...dddddddd...",
        "..............",
        "..............",
    ],
    "four_alarm": [
        "....P.........",
        "...PnP...P....",
        "...PnP..PnP...",
        "..PnYnPPnYP...",
        "..PnYYnPnYnP..",
        ".PnYyyYnYyYnP.",
        ".PnYyyyYYyyYP.",
        ".PnYyyyyyyyYP.",
        "..PnYyyyyyYP..",
        "...PPnnnnPP...",
        "..............",
        "zzzzzzzzzzzzzz",
        "ZZZZZZZZZZZZZZ",
        "..............",
    ],
    "crossroads": [
        "YY.........YY.",
        "YoY.......YoY.",
        ".YoY.....YoY..",
        "..YoY...YoY...",
        "...YoY.YoY....",
        "....YoYoY.....",
        ".....YoY......",
        "....YoYoY.....",
        "...YoY.YoY....",
        "..YoY...YoY...",
        ".YoY.....YoY..",
        "YoY.......YoY.",
        "YY....XX...YY.",
        "......Xz......",
    ],
    "red_hot": [
        "........MM....",
        ".......MgM....",
        "......MMg.....",
        ".....PPPPr....",
        "....PpPPPr....",
        "...PpPPPPr....",
        "..PpPPPPr.....",
        "..PPPPPr......",
        ".PPPPPr.......",
        ".PPPPr........",
        "PPPr..........",
        "Pr............",
        "..............",
        "..............",
    ],
    "overkill": [
        ".......ee.....",
        "....PPPPeP....",
        "..PPcccceccP..",
        ".PccPPPPePcP..",
        ".PcPPccceePP..",
        "PcPPcPYPPecPP.",
        "PcPcPPYYPPPcP.",
        "PcPcPYYYPPceP.",
        "PcPPcPPPPPeee.",
        ".PcPPccccPP...",
        ".PccPPPPPPcP..",
        "..PPcccccPP...",
        "....PPPPP.....",
        "..............",
    ],
    "by_a_thread": [
        "..........x...",
        ".........xX...",
        "........xX....",
        ".......xX.....",
        "......xX......",
        ".....xX..P....",
        "....xX..P.....",
        "...xXX.P......",
        "..xX.XP.......",
        ".xX..P........",
        ".x..P.........",
        "...P..........",
        "..P...........",
        ".P............",
    ],
    "spotless": [
        ".....w....s...",
        "....wsw..sws..",
        ".....w....s...",
        "..s......w....",
        ".sws....www...",
        "..s......w....",
        "...pppppppp...",
        "..pPPPPPPPPr..",
        "..PPwwPPPPPr..",
        "..PPPPPPPPPr..",
        "..PPPPPPPPrr..",
        "...rrrrrrrr...",
        "..............",
        "..............",
    ],
    "grand_slam": [
        "............EE",
        "...........EEd",
        "..........EEd.",
        ".........EEd..",
        "........EEd...",
        ".......EEd....",
        "......EEd.....",
        ".....dd.......",
        "....dd........",
        "..............",
        ".cccc.........",
        "cPccPc........",
        "cccPcc........",
        ".cCCc.........",
    ],
    "full_deck": [
        "..............",
        "....cwwwwwk...",
        "...cwwwwwwk...",
        "..cwPwwwwwk...",
        "..cPPPwwwwk...",
        "..cwPwwwwwk...",
        "..cwwwSwwwk...",
        "..cwwSSSwwk...",
        "..cwwwSwwwk...",
        "..cwwwwwPwk...",
        "..cwwwwPPPk...",
        "..cwwwwwPwk...",
        "..ckkkkkkkk...",
        "..............",
    ],
    "arcade_rookie": [
        "......PP......",
        ".....PppP.....",
        ".....PPPr.....",
        "......rr......",
        "......XX......",
        "......XX......",
        "......XX......",
        "..zzzzXXzzzz..",
        ".zXXXXXXXXXXz.",
        "zXxxxxxxxxxxXz",
        "zXXSXXXXXYXXXz",
        "zXXXXXXXXXXXXz",
        ".ZZZZZZZZZZZZ.",
        "..............",
    ],
    "arcade_regular": [
        "....yYYYYo....",
        "..yYYoooooYo..",
        ".yYoYYYYYYoYo.",
        ".YoYYkkkkYYoO.",
        "yYoYkyyyYkYoYo",
        "YYoYkyYYYkYoYO",
        "YYoYkyYYYkYoYO",
        "YYoYYkkkkYYoYO",
        "oYYoYYYYYYoYO.",
        ".oYYooooooYOO.",
        "..ooYYYYYYOO..",
        "....oooOOO....",
        "..............",
        "..............",
    ],
    "arcade_legend": [
        "..y..y..y.....",
        "..YyyYyyY.....",
        ".hhhhhhhhhhh..",
        "hHyyyyyyyyyHH.",
        "hHttttttttHH..",
        "hHtSSPPtttHH..",
        "hHttYYSStMHH..",
        "hHtttttttMHH..",
        "hHHHHHHHHHHH..",
        "hHYHSHHPHHHH..",
        "hHHHHHHHHHHH..",
        "hHHhhhhhHHHH..",
        "hHHHHHHHHHHH..",
        ".HHHHHHHHHHH..",
    ],
    "blockstorm": [
        "...xxxxxx.....",
        ".xxXXXXXXxx...",
        "xXXXXXXXXXXx..",
        "XXXXXXXXXXXXx.",
        ".zzzzzzzzzzz..",
        "...yY....PP...",
        "..yYo....Pr...",
        ".yYYYYo.......",
        "...yYo..SS....",
        "..yYo...Sb.MM.",
        ".yo........Mg.",
        "..............",
        "..............",
        "..............",
    ],
    "fresh_start": [
        "..............",
        "......M.......",
        "....MMmM.MM...",
        "...MmmMgMmmM..",
        "...MmMgM.MgM..",
        "....MMg.MgM...",
        "......gMg.....",
        "......gg......",
        "......gg......",
        "...EEEEEEEE...",
        "..EeeeeeeeEd..",
        "..EEEEEEEEEd..",
        "...dEEEEEdd...",
        "....dddddd....",
    ],
    "vandal": [
        "..........P.P.",
        ".........P.P.P",
        "......XX...P..",
        ".....XXX..P.P.",
        ".....ww.......",
        "....SSSSb.....",
        "...SsSSSSb....",
        "...SsPPPSb....",
        "...SsPpPSb....",
        "...SsPPPSb....",
        "...SsSSSSb....",
        "...SsSSSSb....",
        "...SSSSSSb....",
        "....bbbbb.....",
    ],
    "night_shift": [
        "..........w...",
        "....yyyy.www..",
        "...yYYo...w...",
        "..yYYo........",
        "..YYo.....w...",
        ".yYYo.........",
        ".YYYo.........",
        ".YYYo.....w...",
        ".oYYYo...www..",
        "..YYYYo...w...",
        "..oYYYYYo..o..",
        "...ooYYYYYo...",
        ".....oooo.....",
        "..............",
    ],
    "no_lines": [
        "....PPPPPP....",
        "..PPrrrrrrPP..",
        ".PPr......PPP.",
        ".Pr......PPrP.",
        "Pr......PPr.rP",
        "Pr.....PPr..rP",
        "PrcccPPrccc.rP",
        "Pr...PPr....rP",
        "Pr..PPr.....rP",
        "Pr.PPr......rP",
        ".PPPr......rP.",
        ".PPr......rrP.",
        "..PPrrrrrrPP..",
        "....PPPPPP....",
    ],
    "butterfingers": [
        "..qqqqqqqqqq..",
        "..qwqqqqqqQj..",
        "..qwqqqQqqQj..",
        "..qqqqQqqQQj..",
        "...qqQqqqQj...",
        "...qQqqqQQj...",
        "....qqqQQj....",
        ".....QQjj.....",
        "......Qj......",
        "......Qj......",
        ".......j..q.Q.",
        "....QQQQj.Q..q",
        "...qqqQQQj....",
        "..............",
    ],
    "through_the_window": [
        "EEEEEEEEEEEEEE",
        "EsSSSSEsSSSSSd",
        "EsSS.SEsSSSSSd",
        "Es.....SSSSSSd",
        "EsSP.P..SSSSSd",
        "Es.PPr.SSSSSSd",
        "EEEPrr.EEEEEEd",
        "EsS..SEsSSSSSd",
        "EsSS.SEsSSSSSd",
        "EsSSSSEsSSSSSd",
        "EsSSSSEsSSSSSd",
        "EsSSSSEsSSSSSd",
        "dddddddddddddd",
        "..............",
    ],
    "fine_print": [
        "..cccccccccc..",
        ".cCCCCCCCCCCc.",
        "..ckkkkkkkkC..",
        "..cccccccccC..",
        "..ckkkkkkkcC..",
        "..cccccccccC..",
        "..cxxxxxxxxC..",
        "..cxxxxxxxcC..",
        "..cxxxxxxxxC..",
        "..cccccSSSSC..",
        "..cccccsSbcC..",
        ".cCCCCCCCCCCc.",
        "..cccccccccc..",
        "..............",
    ],
    "_mystery": [
        "....ffffff....",
        "...fFFFFFFf...",
        "..fFF....FFf..",
        "..fF......Ff..",
        "..........Ff..",
        ".........fFf..",
        "........fFf...",
        ".......fFf....",
        "......fFf.....",
        "......fF......",
        "..............",
        "......fF......",
        "......fF......",
        "..............",
    ],
    "block_maniac": [
        "..............",
        ".y....y....y..",
        ".Yy..yYy..yY..",
        ".YYy.YYY.yYY..",
        ".YYYyYYYyYYY..",
        ".YPYYYSYYYMY..",
        ".YYYYYYYYYYY..",
        ".oooooooooooo.",
        ".YhYYYPYYYSY..",
        ".oooooooooooo.",
        "..............",
        "..Pn.YM.Sh.P..",
        "..nY.MS.hP.n..",
        "..............",
    ],
}


def sprite(rows):
    """14x14 ASCII -> 16x16 RGBA with a 1-px ink outline (4-neighbour)."""
    h = len(rows)
    w = max(len(r) for r in rows)
    assert w <= 14 and h <= 14, (w, h, rows[0])
    body = Image.new("RGBA", (CELL, CELL), CLEAR)
    ox = (CELL - w) // 2
    oy = (CELL - h) // 2
    for y, row in enumerate(rows):
        for x, ch in enumerate(row):
            if ch != ".":
                body.putpixel((ox + x, oy + y), PAL[ch])
    out = body.copy()
    for y in range(CELL):
        for x in range(CELL):
            if body.getpixel((x, y))[3] > 0:
                continue
            for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
                nx, ny = x + dx, y + dy
                if 0 <= nx < CELL and 0 <= ny < CELL and body.getpixel((nx, ny))[3] > 0:
                    out.putpixel((x, y), INK)
                    break
    return out


def glint(base, step):
    """A 3-px diagonal band of light at position `step` (1..6) across the opaque pixels."""
    im = base.copy()
    center = -6 + step * 7
    for y in range(CELL):
        for x in range(CELL):
            r, g, b, a = base.getpixel((x, y))
            if a == 0 or (r, g, b, a) == INK:
                continue
            d = abs((x + y) - center)
            if d <= 1:
                k = 0.75 if d == 0 else 0.4
                im.putpixel((x, y), (int(r + (255 - r) * k), int(g + (255 - g) * k), int(b + (255 - b) * k), a))
    return im


def silhouette(base):
    im = base.copy()
    for y in range(CELL):
        for x in range(CELL):
            if base.getpixel((x, y))[3] > 0:
                im.putpixel((x, y), (46, 32, 68, 255) if base.getpixel((x, y)) != INK else (26, 16, 38, 255))
    return im


def sheet(sprites):
    im = Image.new("RGBA", (CELL * FRAMES, CELL * max(1, len(sprites))), CLEAR)
    index = {}
    for row, (key, rows) in enumerate(sprites.items()):
        base = sprite(rows)
        frames = [base] + [glint(base, s) for s in range(1, 7)] + [silhouette(base)]
        for f, fr in enumerate(frames):
            im.paste(fr, (f * CELL, row * CELL))
        index[key] = row
    return im, index


def badge(tier):
    """A chamfered medal: ink edge, bevelled rim in the tier's ramp, a dark recess for the icon,
    rivets at the corners and a little crest on top. Legendary rims get prism stripes."""
    light, mid, dark, deep = BADGE_TIERS[tier]
    im = Image.new("RGBA", (BADGE, BADGE), CLEAR)
    def inside(x, y, w, h, cut, ox=0, oy=0):
        x -= ox
        y -= oy
        if x < 0 or y < 0 or x >= w or y >= h:
            return False
        return min(x, w - 1 - x) + min(y, h - 1 - y) >= cut
    prism = [(255, 110, 130, 255), (255, 176, 80, 255), (255, 226, 90, 255), (110, 230, 160, 255), (100, 180, 255, 255), (190, 130, 255, 255)]
    for y in range(BADGE):
        for x in range(BADGE):
            if not inside(x, y, BADGE, BADGE, 5):
                continue
            edge = not all(inside(x + dx, y + dy, BADGE, BADGE, 5) for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)))
            if edge:
                im.putpixel((x, y), INK)
                continue
            if inside(x, y, 18, 18, 3, 3, 3):
                # Recess: a soft top-to-bottom gradient, ink lip on the top edge.
                c = tuple(int(v * 0.7) for v in deep[:3]) + (255,) if y > 12 else deep
                if not inside(x, y - 1, 18, 18, 3, 3, 3):
                    c = INK
                im.putpixel((x, y), c)
                continue
            if tier == "legend":
                c = prism[((x + y) // 3) % len(prism)]
                if x + y < 16:
                    c = tuple(min(255, v + 50) for v in c[:3]) + (255,)
                elif x + y > 30:
                    c = tuple(int(v * 0.72) for v in c[:3]) + (255,)
            else:
                c = light if x + y < 12 else (mid if x + y < 32 else dark)
            im.putpixel((x, y), c)
    for bx, by in ((5, 3), (18, 3), (5, 20), (18, 20)):
        im.putpixel((bx, by), light)
    return im


def contact(sheets, path, scale=4):
    """Dev preview: every rest-pose sprite on a plum backdrop with its name (no text: order)."""
    items = [(s, k, r) for s, (im, idx) in sheets.items() for k, r in idx.items()]
    cols = 12
    rows = (len(items) + cols - 1) // cols
    pad = 4
    out = Image.new("RGBA", (cols * (CELL + pad) * scale, rows * (CELL + pad) * scale), (63, 43, 94, 255))
    for i, (s, k, r) in enumerate(items):
        im = sheets[s][0].crop((0, r * CELL, CELL, r * CELL + CELL)).resize((CELL * scale, CELL * scale), Image.NEAREST)
        out.alpha_composite(im, ((i % cols) * (CELL + pad) * scale, (i // cols) * (CELL + pad) * scale))
    out.save(path)


# Engine update sprites (new Jokers, Legendaries, items, Rack Extender, achievement page 5).
import cards_engine  # noqa: E402
JOKERS.update(cards_engine.JOKERS)
ITEMS.update(cards_engine.ITEMS)
TOOLS.update(cards_engine.TOOLS)
ACHIEVEMENTS.update(cards_engine.ACHIEVEMENTS)


def main():
    os.makedirs(OUT, exist_ok=True)
    sets = {"jokers": JOKERS, "items": ITEMS, "tools": TOOLS, "achievements": ACHIEVEMENTS}
    built = {}
    index = {}
    for name, sprites in sets.items():
        im, idx = sheet(sprites)
        im.save(os.path.join(OUT, name + ".png"))
        built[name] = (im, idx)
        index[name] = idx
    frames = Image.new("RGBA", (BADGE * len(BADGE_TIERS), BADGE), CLEAR)
    for i, tier in enumerate(BADGE_TIERS):
        frames.paste(badge(tier), (i * BADGE, 0))
    frames.save(os.path.join(OUT, "badges.png"))
    index["badges"] = {tier: i for i, tier in enumerate(BADGE_TIERS)}
    with open(os.path.join(OUT, "cards.json"), "w") as f:
        json.dump(index, f, indent=1, sort_keys=True)
    if len(sys.argv) > 1:
        contact(built, sys.argv[1])
    print("wrote", ", ".join("%s %d" % (k, len(v)) for k, v in sets.items()), "sprites to", OUT)


if __name__ == "__main__":
    main()
