class_name BMAudio
extends Node
## Sound effects and music. Presentation only: nothing here reads or changes rules state, and
## cosmetic randomness (variants, pitch jitter, shuffle) uses the global RNG, never the run's.
##
## Buses: Master -> Music, SFX (created at startup). Every sound file is generated by
## tools/audio/ (gen_sfx.py, gen_music.py); relative loudness is baked into the files.

static var instance: BMAudio

const SFX_DIR := "res://assets/audio/sfx/"
const MUSIC_DIR := "res://assets/audio/music/"

## id -> [file variants, random pitch spread, minimum ms between plays].
const SFX := {
	"hover": [["ui_hover_1", "ui_hover_2"], 0.04, 45],
	"click": [["ui_click_1", "ui_click_2"], 0.03, 40],
	"back": [["ui_back"], 0.02, 60],
	"toggle_on": [["ui_toggle_on"], 0.0, 60],
	"toggle_off": [["ui_toggle_off"], 0.0, 60],
	"tick": [["ui_tick"], 0.0, 25],
	"card_hover": [["card_hover"], 0.08, 70],
	"modal": [["modal_open"], 0.03, 120],
	"pause_in": [["pause_in"], 0.0, 150],
	"pause_out": [["pause_out"], 0.0, 150],
	"bag_open": [["bag_open"], 0.04, 150],
	"bag_close": [["bag_close"], 0.04, 150],
	"select": [["select"], 0.02, 40],
	"deselect": [["deselect"], 0.02, 40],
	"pickup": [["pickup"], 0.05, 50],
	"putback": [["putback"], 0.05, 50],
	"key_move": [["key_move"], 0.03, 20],
	"place_s": [["place_s_1", "place_s_2", "place_s_3"], 0.03, 30],
	"place_m": [["place_m_1", "place_m_2", "place_m_3"], 0.03, 30],
	"place_l": [["place_l_1", "place_l_2", "place_l_3"], 0.03, 30],
	"deny": [["deny"], 0.0, 150],
	"pop": [["pop"], 0.0, 18],
	"glass": [["glass"], 0.06, 60],
	"stamp": [["stamp"], 0.04, 60],
	"clear_1": [["clear_1"], 0.0, 80],
	"clear_2": [["clear_2"], 0.0, 80],
	"clear_3": [["clear_3"], 0.0, 80],
	"combo_1": [["combo_1"], 0.0, 80],
	"combo_2": [["combo_2"], 0.0, 80],
	"combo_3": [["combo_3"], 0.0, 80],
	"joker_chips": [["joker_chips"], 0.0, 40],
	"joker_mult": [["joker_mult"], 0.0, 40],
	"joker_xmult": [["joker_xmult"], 0.0, 40],
	"coin": [["coin_1", "coin_2"], 0.03, 45],
	"buy": [["buy"], 0.02, 100],
	"sell": [["sell"], 0.02, 100],
	"reroll": [["reroll"], 0.02, 100],
	"workshop": [["workshop"], 0.02, 100],
	"item": [["item_use"], 0.02, 100],
	"refresh": [["refresh"], 0.02, 100],
	"deal": [["deal"], 0.06, 30],
	"print": [["print_tick"], 0.1, 30],
	"score": [["score_whoosh"], 0.04, 120],
	"alert": [["alert"], 0.0, 400],
	"letter": [["letter"], 0.0, 20],
	"sting_round": [["sting_round"], 0.0, 500],
	"sting_boss": [["sting_boss"], 0.0, 500],
	"jingle_win": [["jingle_win"], 0.0, 500],
	"jingle_run_win": [["jingle_run_win"], 0.0, 500],
	"jingle_lose": [["jingle_lose"], 0.0, 500],
}

## Soundtrack. Order inside a playlist is shuffled (never the same track twice in a row).
const TRACKS := {
	"blockhead_lullaby": "Blockhead Lullaby",
	"eight_by_eight": "Eight by Eight",
	"rainy_arcade": "Rainy Arcade",
	"clear_skies": "Clear Skies",
	"night_shift": "Night Shift",
	"the_toybox": "The Toybox",
	"last_call": "Last Call",
}
const PLAYLISTS := {
	"title": ["blockhead_lullaby"],
	"round": ["eight_by_eight", "rainy_arcade", "clear_skies", "night_shift"],
	"shop": ["the_toybox"],
	"boss": ["last_call"],
	"endless_calm": ["blockhead_lullaby", "rainy_arcade", "clear_skies"],
	"endless_tense": ["night_shift", "last_call"],
	"endless_party": ["the_toybox", "eight_by_eight"],
	"endless_clean": ["clear_skies", "the_toybox"],
}
const TRACK_BPM := {"blockhead_lullaby": 64, "eight_by_eight": 76, "rainy_arcade": 70,
	"clear_skies": 84, "night_shift": 80, "the_toybox": 92, "last_call": 68}
const TRACK_BEATS := {"clear_skies": 3}
## A breath of silence between tracks, like an ambient soundtrack (seconds).
const GAP := Vector2(2.5, 6.0)
const CROSSFADE := 1.6
const POOL := 20

## Scale steps for the cascading cell pops (major pentatonic ratios).
const PENTA := [1.0, 1.1225, 1.2599, 1.4983, 1.6818, 2.0, 2.2449, 2.5198, 2.9966, 3.3636]

var _streams := {}
var _pool: Array[AudioStreamPlayer] = []
var _next := 0
var _last_ms := {}
var _music: Array[AudioStreamPlayer] = []
var _combo_layer: AudioStreamPlayer
var _combo_level := 0
var _combo_fade: Tween
var _combo_loops := {}
var _combo_track := ""
var _skin_streams := {}
var _active := 0
var _fade: Tween
var _context := ""
var _track := ""
var _history: Array[String] = []
var _gap_timer: SceneTreeTimer
var _lowpass: AudioEffectLowPassFilter
var _muffled := false
var _settings := {}
var _focused := true


func _ready() -> void:
	instance = self
	process_mode = Node.PROCESS_MODE_ALWAYS
	_setup_buses()
	for id in SFX:
		for f in SFX[id][0]:
			var path: String = SFX_DIR + f + ".wav"
			if ResourceLoader.exists(path):
				_streams[f] = load(path)
			else:
				push_warning("BMAudio: missing sound %s" % path)
	for i in POOL:
		var p := AudioStreamPlayer.new()
		p.bus = "SFX"
		add_child(p)
		_pool.append(p)
	for i in 2:
		var m := AudioStreamPlayer.new()
		m.bus = "Music"
		m.finished.connect(_on_track_finished.bind(m))
		add_child(m)
		_music.append(m)
	_combo_layer = AudioStreamPlayer.new()
	_combo_layer.bus = "Music"
	_combo_layer.volume_db = -60.0
	add_child(_combo_layer)


func _exit_tree() -> void:
	if instance == self:
		instance = null


func _setup_buses() -> void:
	for bus_name in ["Music", "SFX"]:
		if AudioServer.get_bus_index(bus_name) == -1:
			AudioServer.add_bus()
			var idx := AudioServer.bus_count - 1
			AudioServer.set_bus_name(idx, bus_name)
			AudioServer.set_bus_send(idx, "Master")
	var mi := AudioServer.get_bus_index("Music")
	if AudioServer.get_bus_effect_count(mi) == 0:
		_lowpass = AudioEffectLowPassFilter.new()
		_lowpass.cutoff_hz = 900.0
		AudioServer.add_bus_effect(mi, _lowpass, 0)
	else:
		_lowpass = AudioServer.get_bus_effect(mi, 0) as AudioEffectLowPassFilter
	AudioServer.set_bus_effect_enabled(mi, 0, false)


# --- Settings --------------------------------------------------------------------------------

## Reads master/music/sfx volumes (0..1) and the mute flags from the settings dictionary.
func apply_settings(s: Dictionary) -> void:
	_settings = s
	_set_bus("Master", float(s.get("master_volume", 0.8)), bool(s.get("muted", false)) or (not _focused and bool(s.get("mute_unfocused", false))))
	_set_bus("Music", float(s.get("music_volume", 0.6)), not bool(s.get("music_on", true)), -4.0 if _muffled else 0.0)
	_set_bus("SFX", float(s.get("sfx_volume", 0.8)), false)


func _set_bus(bus_name: String, volume: float, mute: bool, trim_db: float = 0.0) -> void:
	var idx := AudioServer.get_bus_index(bus_name)
	if idx < 0:
		return
	# Perceptual curve: squared slider value feels even across the range.
	AudioServer.set_bus_volume_db(idx, linear_to_db(maxf(volume * volume, 0.00001)) + trim_db)
	AudioServer.set_bus_mute(idx, mute or volume <= 0.001)


func _notification(what: int) -> void:
	if what == NOTIFICATION_APPLICATION_FOCUS_OUT or what == NOTIFICATION_APPLICATION_FOCUS_IN:
		_focused = what == NOTIFICATION_APPLICATION_FOCUS_IN
		if not _settings.is_empty():
			apply_settings(_settings)


# --- Sound effects ---------------------------------------------------------------------------

## Play a sound effect by id. Safe to call when audio is not set up (does nothing).
static func sfx(id: String, pitch: float = 1.0, volume_db: float = 0.0) -> void:
	if instance != null:
		instance._play(id, pitch, volume_db)


## Play later without capturing any node (timers outlive screens).
static func sfx_later(id: String, delay: float, pitch: float = 1.0, volume_db: float = 0.0) -> void:
	if instance == null:
		return
	if delay <= 0.0:
		instance._play(id, pitch, volume_db)
		return
	instance.get_tree().create_timer(delay, true).timeout.connect(func() -> void:
		if BMAudio.instance != null:
			BMAudio.instance._play(id, pitch, volume_db))


## Pitch for the n-th step of an ascending pentatonic cascade.
static func scale_pitch(step: int) -> float:
	return PENTA[clampi(step, 0, PENTA.size() - 1)]


func _play(id: String, pitch: float, volume_db: float) -> void:
	var def: Array = SFX.get(id, [])
	if def.is_empty():
		push_warning("BMAudio: unknown sfx '%s'" % id)
		return
	var now := Time.get_ticks_msec()
	if now - int(_last_ms.get(id, -100000)) < int(def[2]):
		return
	_last_ms[id] = now
	var files: Array = def[0]
	var stream: AudioStream = _streams.get(files[randi() % files.size()])
	if stream == null:
		return
	var p := _pool[_next]
	_next = (_next + 1) % _pool.size()
	p.stream = stream
	p.pitch_scale = maxf(0.05, pitch * (1.0 + randf_range(-def[1], def[1])))
	p.volume_db = volume_db
	p.play()


## Short original per-finish cues, generated as PCM when a finish is first used.
static func skin_sfx(skin: String, clear: bool = false) -> void:
	if instance != null and skin != "classic":
		instance._play_skin(skin, clear)


func _play_skin(skin: String, clear: bool) -> void:
	var idx := BMBlockPainter.ENDLESS_SKINS.find(skin)
	if idx < 0:
		return
	var key := skin + ("_clear" if clear else "_place")
	if not _skin_streams.has(key):
		_skin_streams[key] = _make_skin_cue(idx, clear)
	var player := _pool[_next]
	_next = (_next + 1) % _pool.size()
	player.stream = _skin_streams[key]
	player.pitch_scale = 1.0
	player.volume_db = -7.0
	player.play()


func _make_skin_cue(index: int, clear: bool) -> AudioStreamWAV:
	const RATE := 22050
	var duration := 0.37 if clear else 0.16
	var count := roundi(RATE * duration)
	var pcm := PackedByteArray()
	pcm.resize(count * 2)
	var pitches := [290.0, 700.0, 880.0, 600.0, 420.0, 370.0, 540.0,
		250.0, 640.0, 190.0, 760.0, 500.0, 810.0, 960.0]
	var base: float = pitches[index]
	for i in count:
		var t := float(i) / RATE
		var sweep := base * (1.0 + (0.22 if clear else -0.16) * t / duration)
		var wave := sin(TAU * sweep * t) + 0.35 * sin(TAU * sweep * t * (2.0 + float(index % 3)))
		var hash_value := (i * 1103515245 + index * 9176 + 12345) & 0x7fffffff
		var noise := float(hash_value) / 1073741823.5 - 1.0
		var gritty := 0.18 if index in [6, 7, 9] else 0.06
		var envelope := (1.0 - exp(-t * 90.0)) * exp(-t * (8.0 if clear else 19.0))
		var sample := clampi(roundi((wave * 0.23 + noise * gritty) * envelope * 32767.0), -32768, 32767)
		pcm[i * 2] = sample & 255
		pcm[i * 2 + 1] = (sample >> 8) & 255
	var wav := AudioStreamWAV.new()
	wav.format = AudioStreamWAV.FORMAT_16_BITS
	wav.mix_rate = RATE
	wav.stereo = false
	wav.data = pcm
	return wav


# --- Music -----------------------------------------------------------------------------------

## Switch the music context ("title", "round", "boss", "shop"). The current track keeps
## playing if it already belongs to the new context.
static func music(context: String) -> void:
	if instance != null:
		instance._set_context(context)


func _set_context(context: String) -> void:
	if context == _context:
		return
	_context = context
	if _track != "" and _any_music_playing() and PLAYLISTS.get(context, []).has(_track):
		return
	_start_track(_pick(context), true)


## A quiet beat layer joins the original Endless soundtrack at x5 and grows at x8.
## Its rhythm is synthesized in code and aligned to the current track's BPM.
static func set_endless_combo(level: int) -> void:
	if instance != null:
		instance._set_endless_combo(level)


func _set_endless_combo(level: int) -> void:
	if level == _combo_level:
		return
	_combo_level = level
	if _combo_fade != null and _combo_fade.is_running():
		_combo_fade.kill()
	if level >= 5:
		_sync_combo_layer()
	_combo_fade = create_tween()
	_combo_fade.tween_property(_combo_layer, "volume_db", -8.0 if level >= 8 else (-13.0 if level >= 5 else -60.0), 0.55)
	if level < 5:
		_combo_fade.tween_callback(func() -> void:
			if _combo_level < 5:
				_combo_layer.stop())


func _sync_combo_layer(force := false) -> void:
	if _combo_level < 5 or _track == "" or not _music[_active].playing:
		return
	if not force and _combo_layer.playing and _combo_track == _track:
		return
	var bpm: int = TRACK_BPM.get(_track, 76)
	var beats: int = TRACK_BEATS.get(_track, 4)
	var key := "%d/%d" % [bpm, beats]
	if not _combo_loops.has(key):
		_combo_loops[key] = _make_combo_loop(bpm, beats)
	_combo_layer.stop()
	_combo_layer.stream = _combo_loops[key]
	_combo_track = _track
	var bar_seconds := 60.0 * beats / float(bpm)
	_combo_layer.play(fposmod(_music[_active].get_playback_position(), bar_seconds))


func _make_combo_loop(bpm: int, beats: int) -> AudioStreamWAV:
	const RATE := 22050
	var count := roundi(RATE * 60.0 * beats / float(bpm))
	var pcm := PackedByteArray()
	pcm.resize(count * 2)
	for i in count:
		var beat := float(i) * float(bpm) / (60.0 * RATE)
		var beat_index := int(floorf(beat))
		var beat_time := fposmod(beat, 1.0) * 60.0 / float(bpm)
		var half_time := fposmod(beat * 2.0, 1.0) * 30.0 / float(bpm)
		var hash_value := (i * 1103515245 + 12345) & 0x7fffffff
		var noise := float(hash_value) / 1073741823.5 - 1.0
		var value := 0.0
		if beat_index % 2 == 0 and beat_time < 0.24:
			value += sin(TAU * (72.0 * beat_time - 30.0 * beat_time * beat_time)) * exp(-beat_time * 24.0) * 0.26
		if beat_index % 2 == 1 and beat_time < 0.15:
			value += noise * exp(-beat_time * 28.0) * 0.18
		if half_time < 0.06:
			value += noise * exp(-half_time * 55.0) * (0.10 if beat_index % 2 == 0 else 0.14)
		var sample := clampi(roundi(value * 32767.0), -32768, 32767)
		pcm[i * 2] = sample & 255
		pcm[i * 2 + 1] = (sample >> 8) & 255
	var wav := AudioStreamWAV.new()
	wav.format = AudioStreamWAV.FORMAT_16_BITS
	wav.mix_rate = RATE
	wav.stereo = false
	wav.data = pcm
	wav.loop_mode = AudioStreamWAV.LOOP_FORWARD
	wav.loop_begin = 0
	wav.loop_end = count
	return wav


func _process(_delta: float) -> void:
	if _combo_level >= 5:
		if not _music[_active].playing:
			_combo_layer.stop()
		elif not _combo_layer.playing:
			_sync_combo_layer()


func skip_track() -> void:
	if _context != "":
		_start_track(_pick(_context), true)


func now_playing() -> String:
	return TRACKS.get(_track, "") if _any_music_playing() else ""


## Muffle the music behind menus (low-pass + a little quieter).
func set_muffled(on: bool) -> void:
	if on == _muffled:
		return
	_muffled = on
	var mi := AudioServer.get_bus_index("Music")
	AudioServer.set_bus_effect_enabled(mi, 0, on)
	# A menu may open during a crossfade. Keep its fade in progress and apply the
	# attenuation at the bus, so the two player tweens cannot fight each other.
	apply_settings(_settings)


func _pick(context: String) -> String:
	var list: Array = PLAYLISTS.get(context, [])
	if list.is_empty():
		return ""
	if list.size() == 1:
		return list[0]
	var options := list.filter(func(t: String) -> bool: return t != _track and not _history.slice(-2).has(t))
	if options.is_empty():
		options = list.filter(func(t: String) -> bool: return t != _track)
	return options[randi() % options.size()]


func _start_track(id: String, crossfade: bool) -> void:
	_gap_timer = null
	if id == "":
		return
	var path := MUSIC_DIR + id + ".ogg"
	if not ResourceLoader.exists(path):
		push_warning("BMAudio: missing track %s" % path)
		return
	if _fade and _fade.is_running():
		_fade.kill()
	var old := _music[_active]
	_active = 1 - _active
	var nxt := _music[_active]
	nxt.stop()
	nxt.stream = load(path)
	_track = id
	_history.append(id)
	if _history.size() > 8:
		_history.pop_front()
	# With music switched off the bus is muted and the playlist simply runs silently.
	if crossfade and old.playing:
		nxt.volume_db = -40.0
		nxt.play()
		_fade = create_tween().set_parallel(true)
		_fade.tween_property(nxt, "volume_db", 0.0, CROSSFADE)
		_fade.tween_property(old, "volume_db", -40.0, CROSSFADE)
		_fade.chain().tween_callback(old.stop)
	else:
		old.stop()
		nxt.volume_db = 0.0
		nxt.play()
	_sync_combo_layer(true)


func _on_track_finished(player: AudioStreamPlayer) -> void:
	if player != _music[_active]:
		return
	# Leave a short silence, then continue the playlist.
	var t := get_tree().create_timer(randf_range(GAP.x, GAP.y), true)
	_gap_timer = t
	t.timeout.connect(func() -> void:
		if _gap_timer == t:
			_start_track(_pick(_context), false))


func _any_music_playing() -> bool:
	for m in _music:
		if m.playing:
			return true
	return false
